sudo: true

language: go

go:
  - "1.10.x"

service:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - cd kubeplay
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o goserv .
      - cd ..
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/kubeplay:0.1.0 -f images/kubeplay/Dockerfile .
      - docker images
      - docker push $DOCKER_USERNAME/kubeplay:0.1.0
    - stage: test
      script:
      - docker run -d -p 127.0.0.1:8080:8080 --name hello $DOCKER_USERNAME/kubeplay:0.1.0
      - docker ps | grep -q hello
      - curl -vsf 'http://127.0.0.1:8080/index.html' &> /dev/stdout
