sudo: true
dist: xenial

jobs:
  include:
    - stage: build docker image
      script:
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build -t $DOCKER_USERNAME/kubeplay:arm32v7 images/kubeplay
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/kubeplay:arm32v7
    - stage: test
      script:
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker run --rm $DOCKER_USERNAME/kubeplay:arm32v7
